# Base image with Python
FROM python:3.12-slim

# Install system dependencies for Scapy (libpcap for packet capture)
RUN apt-get update && apt-get install -y libpcap-dev && rm -rf /var/lib/apt/lists/*

# Install Scapy
RUN pip install scapy

# Copy the script into the container
COPY app.py .

# Set working directory
WORKDIR /app

# Default command (can override with docker run args)
CMD ["python", "../app.py", "--iface=all", "--timeout=60", "--output=/output/test.csv"]
